version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/frontend"
      - "/backend"
    schedule:
      interval: monthly
    groups:
      dependencies:
        applies-to: version-updates
        patterns:
          - "*"
      security:
        applies-to: security-updates
        patterns:
          - "*"
