version: 2
updates:
  - package-ecosystem: "bun"
    directories: 
      - "/frontend"
      - "/backend"
    schedule:
      interval: monthly
    groups:
      dependencies:
        applies-to: version-updates
        patterns:
          - "*"